//BEHAVIOR: FOLLOW, TAKE, DROP, PUSH
//LOGIC: ID of objects it will interact with e.g TAKE object with DROP
//DOORS: ID of door objects (only works with drop for now) and limited to 1x3 doors

module.exports = {
  API_KEY: "Yp9mowc2viQlq8xT", // info@raidheroom.com
  // API_KEY: "Cu4tlS6CIU6iWjcG", // kevin@raidheroom.com
  
  // url: "kuOpQ63ckdxpfANU\\kevinwebsockets",
  // SPACE_ID: "kuOpQ63ckdxpfANU\\kevinwebsockets",

  url: "oimL5gsmKZJcFExW\\mastermind-demo",
  SPACE_ID: "oimL5gsmKZJcFExW\\mastermind-demo",

  // url: "Ho6abUIslqoWcDQ7\\gamifygather-scavaganza",
  // SPACE_ID: "Ho6abUIslqoWcDQ7\\gamifygather-scavaganza",

  // BetaDwarf Office
  // url: "m5UqybVLl1KttCij\\office",
  // SPACE_ID: "m5UqybVLl1KttCij\\office",

  MAP_ID: [
    "mastermind"
    // "betadwarf-mastermind"  
    // "test-room"
    // "custom-entrance"
    // "knights-room-puzzle-run"
    // "storefront", // This map references all of the code in KEVINWEBSOCKETS_TEST, so if I add another map, then I need antoher All_OBJECTS room/list of objects
    // 

  ],
  STATUE: {
    "off": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/internal-dashboard/images/twIKv7bnw-CLPwyfYsO-E",
    "on": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/internal-dashboard/images/A_4_wAmZIAazGZoGYrCgW"
  },
  DOORS: {
    "open": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FOAS5P91MeHHJ9X3x?alt=media&token=5cbaf712-c15f-47ca-9a35-160831d22ffd",
    "close": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2F2NUrsU3ek8g60Yez?alt=media&token=7ee54bfe-0594-42e0-95e8-0befc2064521",
  },
  ARROW_DIR: {
    "down": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2F6BgVETZfCGaKPA2T?alt=media&token=cc32fda4-d498-4593-8547-7675f1e561cb",
    "left": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FvxC2LnC8H1ltvP1S?alt=media&token=409d5b82-8b11-47ed-b145-c4b55b65da8d",
    "up": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FnQIEQCMu2OBHi20G?alt=media&token=d6462a6e-df94-416e-afdc-d54d6a1e3c7e",
    "right": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2F2lmHBWwOnr066bTe?alt=media&token=3aa45e8f-795d-4e34-9829-a23c5dc3c66d",
  },
  BLANK: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
  PLATE: {
    "glass": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FYEeExcvH2DBnZsrI?alt=media&token=1b8fcb20-960f-40ec-b8b8-2a8496123e59"
  },
  BRAIN: "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/internal-dashboard/images/8WKeYhaQDxaW7P7IBFSqv",

  ALL_OBJECTS: {
    KEVIN_WEBSOCKETS: {
      "note": {
        "id": "note",
        "type": 7,
        "x": 23,
        "y": 12,
        "width": 1,
        "height": 1,
        "distThreshold": 2,
        "previewMessage": "Press x to leave a note for others during this game.",
        "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=[Leave a note during this game]&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
        "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=[Leave a note during this game]&font=Roboto-Regular.ttf&red=255&green=255&blue=0&size=14",
        "customState": "none",
        'COOLDOWN': 0,
        'BEHAVIOR': 'none',
        'FIXED': true,
        'LOGIC': 'none',
        'DOORS': 'none',
        'SWAPPABLE': false,
        'STACKABLE': false,
        'TRADEABLE': false,
        'LOOTABLE': false,
        "properties": {
          extensionData: {
              entries: [
                  {
                      type: "header",
                      value: "Submit text below to leave your shared note here.",
                      key: "start_header"
                  },
                  {
                    type: "text",
                    value: "Enter your note here",
                    key: "secret_word",
                  },
                                        
              ]
          }
        }
      
    },

    "start": {
      "id": "start",
      "type": 7,
      "x": 12,
      "y": 13,
      "width": 1,
      "height": 1,
      "distThreshold": 2,
      "previewMessage": "Press x to start a new game.",
      "normal": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/9g1r0WE8y6Fgb9VanyCxJx",
      "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/2GHxbsaHYPUKCrbsnM4n9b",
      "customState": "none",
      'COOLDOWN': 0,
      'BEHAVIOR': 'none',
      'FIXED': true,
      'LOGIC': 'none',
      'DOORS': 'none',
      'SWAPPABLE': false,
      'STACKABLE': false,
      'TRADEABLE': false,
      'LOOTABLE': false,
      "properties": {
        extensionData: {
            entries: [
                {
                    type: "header",
                    value: "Are you sure you want to start a new game?",
                    key: "start_header"
                },
                {
                  type: "radio",
                  key: "radio_input",
                  options: [
                    {
                      label: "No",
                      key: "No",
                    },
                    {
                      label: "Yes",
                      key: "Yes",
                    },
                  ],
                },                 
            ]
        }
      }
    
  },

  "start_text": {
    "id": "start_text",
    "type": 0,
    "x": 9,
    "y": 14,
    "width": 4,
    "height": 1,
    "distThreshold": 1,
    "previewMessage": "Press x to check.",
    "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=New game?&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=16",
    // "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=Game has not started yet&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "status": {
    "id": "status",
    "type": 0,
    "x": 20,
    "y": 14,
    "width": 4,
    "height": 1,
    "distThreshold": 1,
    "previewMessage": "Press x to check.",
    "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=Loading new game...&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=Loading new game...&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },
  "status_2": {
    "id": "status_2",
    "type": 0,
    "x": 20,
    "y": 15,
    "width": 4,
    "height": 1,
    "distThreshold": 1,
    "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "check": {
    "id": "check",
    "type": 5,
    "x": 20,
    "y": 12,
    "width": 4,
    "height": 1,
    "distThreshold": 1,
    "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/57VP7npw7WXaVthsvrAHwJ",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/MVKh7TNZo19FTmpYhjsjI1",
    "customState": "none",
    // 'COOLDOWN': 2000,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  

  "guess_0": {
    "id": "guess_0",
    "type": 0,
    "x": 11,
    "y": 12,
    "width": 4,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=18",
    "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=18",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  // "guess_1": {
  //   "id": "guess_1",
  //   "type": 0,
  //   "x": 11,
  //   "y": 10,
  //   "width": 4,
  //   "height": 1,
  //   "distThreshold": 1,
  //   // "previewMessage": "Press x to check.",
  //   "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=1st Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
  //   "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?1st Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
  //   "customState": "none",
  //   'COOLDOWN': 0,
  //   'BEHAVIOR': 'none',
  //   'FIXED': true,
  //   'LOGIC': 'none',
  //   'DOORS': 'none',
  //   'SWAPPABLE': false,
  //   'STACKABLE': true,
  //   'TRADEABLE': false,
  //   'LOOTABLE': false,
  // },

  // "guess_2": {
  //   "id": "guess_2",
  //   "type": 0,
  //   "x": 11,
  //   "y": 9,
  //   "width": 4,
  //   "height": 1,
  //   "distThreshold": 1,
  //   // "previewMessage": "Press x to check.",
  //   "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=2nd Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
  //   "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?2nd Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
  //   "customState": "none",
  //   'COOLDOWN': 0,
  //   'BEHAVIOR': 'none',
  //   'FIXED': true,
  //   'LOGIC': 'none',
  //   'DOORS': 'none',
  //   'SWAPPABLE': false,
  //   'STACKABLE': true,
  //   'TRADEABLE': false,
  //   'LOOTABLE': false,
  // },

  // "guess_3": {
  //   "id": "guess_3",
  //   "type": 0,
  //   "x": 11,
  //   "y": 8,
  //   "width": 4,
  //   "height": 1,
  //   "distThreshold": 1,
  //   // "previewMessage": "Press x to check.",
  //   "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=3rd Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
  //   "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?3rd Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
  //   "customState": "none",
  //   'COOLDOWN': 0,
  //   'BEHAVIOR': 'none',
  //   'FIXED': true,
  //   'LOGIC': 'none',
  //   'DOORS': 'none',
  //   'SWAPPABLE': false,
  //   'STACKABLE': true,
  //   'TRADEABLE': false,
  //   'LOOTABLE': false,
  // },

  // "guess_4": {
  //   "id": "guess_4",
  //   "type": 0,
  //   "x": 11,
  //   "y": 7,
  //   "width": 4,
  //   "height": 1,
  //   "distThreshold": 1,
  //   // "previewMessage": "Press x to check.",
  //   "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=4th Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
  //   "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?4th Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
  //   "customState": "none",
  //   'COOLDOWN': 0,
  //   'BEHAVIOR': 'none',
  //   'FIXED': true,
  //   'LOGIC': 'none',
  //   'DOORS': 'none',
  //   'SWAPPABLE': false,
  //   'STACKABLE': true,
  //   'TRADEABLE': false,
  //   'LOOTABLE': false,
  // },

  // "guess_5": {
  //   "id": "guess_5",
  //   "type": 0,
  //   "x": 11,
  //   "y": 6,
  //   "width": 4,
  //   "height": 1,
  //   "distThreshold": 1,
  //   // "previewMessage": "Press x to check.",
  //   "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=5th Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
  //   "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?5th Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
  //   "customState": "none",
  //   'COOLDOWN': 0,
  //   'BEHAVIOR': 'none',
  //   'FIXED': true,
  //   'LOGIC': 'none',
  //   'DOORS': 'none',
  //   'SWAPPABLE': false,
  //   'STACKABLE': true,
  //   'TRADEABLE': false,
  //   'LOOTABLE': false,
  // },

  // "guess_6": {
  //   "id": "guess_6",
  //   "type": 0,
  //   "x": 11,
  //   "y": 5,
  //   "width": 4,
  //   "height": 1,
  //   "distThreshold": 1,
  //   // "previewMessage": "Press x to check.",
  //   "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=6th Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
  //   "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?6th Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
  //   "customState": "none",
  //   'COOLDOWN': 0,
  //   'BEHAVIOR': 'none',
  //   'FIXED': true,
  //   'LOGIC': 'none',
  //   'DOORS': 'none',
  //   'SWAPPABLE': false,
  //   'STACKABLE': true,
  //   'TRADEABLE': false,
  //   'LOOTABLE': false,
  // },

  // "guess_7": {
  //   "id": "guess_7",
  //   "type": 0,
  //   "x": 11,
  //   "y": 4,
  //   "width": 4,
  //   "height": 1,
  //   "distThreshold": 1,
  //   // "previewMessage": "Press x to check.",
  //   "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=7th Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
  //   "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?7th Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
  //   "customState": "none",
  //   'COOLDOWN': 0,
  //   'BEHAVIOR': 'none',
  //   'FIXED': true,
  //   'LOGIC': 'none',
  //   'DOORS': 'none',
  //   'SWAPPABLE': false,
  //   'STACKABLE': true,
  //   'TRADEABLE': false,
  //   'LOOTABLE': false,
  // },

  // "guess_8": {
  //   "id": "guess_8",
  //   "type": 0,
  //   "x": 11,
  //   "y": 3,
  //   "width": 4,
  //   "height": 1,
  //   "distThreshold": 1,
  //   // "previewMessage": "Press x to check.",
  //   "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=8th Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
  //   "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?8th Guess:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
  //   "customState": "none",
  //   'COOLDOWN': 0,
  //   'BEHAVIOR': 'none',
  //   'FIXED': true,
  //   'LOGIC': 'none',
  //   'DOORS': 'none',
  //   'SWAPPABLE': false,
  //   'STACKABLE': true,
  //   'TRADEABLE': false,
  //   'LOOTABLE': false,
  // },

  "final_answer": {
    "id": "final_answer",
    "type": 0,
    "x": 11,
    "y": 2,
    "width": 4,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=Final Answer:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?Final Answer:&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_1_1": {
    "id": "guess_1_1",
    "type": 0,
    "x": 14,
    "y": 10,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_1_2": {
    "id": "guess_1_2",
    "type": 0,
    "x": 15,
    "y": 10,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_1_3": {
    "id": "guess_1_3",
    "type": 0,
    "x": 16,
    "y": 10,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_1_4": {
    "id": "guess_1_4",
    "type": 0,
    "x": 17,
    "y": 10,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_2_1": {
    "id": "guess_2_1",
    "type": 0,
    "x": 14,
    "y": 9,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_2_2": {
    "id": "guess_2_2",
    "type": 0,
    "x": 15,
    "y": 9,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_2_3": {
    "id": "guess_2_3",
    "type": 0,
    "x": 16,
    "y": 9,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_2_4": {
    "id": "guess_2_4",
    "type": 0,
    "x": 17,
    "y": 9,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_3_1": {
    "id": "guess_3_1",
    "type": 0,
    "x": 14,
    "y": 8,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_3_2": {
    "id": "guess_3_2",
    "type": 0,
    "x": 15,
    "y": 8,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_3_3": {
    "id": "guess_3_3",
    "type": 0,
    "x": 16,
    "y": 8,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_3_4": {
    "id": "guess_3_4",
    "type": 0,
    "x": 17,
    "y": 8,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_4_1": {
    "id": "guess_4_1",
    "type": 0,
    "x": 14,
    "y": 7,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_4_2": {
    "id": "guess_4_2",
    "type": 0,
    "x": 15,
    "y": 7,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_4_3": {
    "id": "guess_4_3",
    "type": 0,
    "x": 16,
    "y": 7,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_4_4": {
    "id": "guess_4_4",
    "type": 0,
    "x": 17,
    "y": 7,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_5_1": {
    "id": "guess_5_1",
    "type": 0,
    "x": 14,
    "y": 6,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_5_2": {
    "id": "guess_5_2",
    "type": 0,
    "x": 15,
    "y": 6,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_5_3": {
    "id": "guess_5_3",
    "type": 0,
    "x": 16,
    "y": 6,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_5_4": {
    "id": "guess_5_4",
    "type": 0,
    "x": 17,
    "y": 6,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_6_1": {
    "id": "guess_6_1",
    "type": 0,
    "x": 14,
    "y": 5,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_6_2": {
    "id": "guess_6_2",
    "type": 0,
    "x": 15,
    "y": 5,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_6_3": {
    "id": "guess_6_3",
    "type": 0,
    "x": 16,
    "y": 5,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_6_4": {
    "id": "guess_6_4",
    "type": 0,
    "x": 17,
    "y": 5,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_7_1": {
    "id": "guess_7_1",
    "type": 0,
    "x": 14,
    "y": 4,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_7_2": {
    "id": "guess_7_2",
    "type": 0,
    "x": 15,
    "y": 4,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_7_3": {
    "id": "guess_7_3",
    "type": 0,
    "x": 16,
    "y": 4,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_7_4": {
    "id": "guess_7_4",
    "type": 0,
    "x": 17,
    "y": 4,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_8_1": {
    "id": "guess_8_1",
    "type": 0,
    "x": 14,
    "y": 3,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_8_2": {
    "id": "guess_8_2",
    "type": 0,
    "x": 15,
    "y": 3,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_8_3": {
    "id": "guess_8_3",
    "type": 0,
    "x": 16,
    "y": 3,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_8_4": {
    "id": "guess_8_4",
    "type": 0,
    "x": 17,
    "y": 3,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_9_1": {
    "id": "guess_9_1",
    "type": 0,
    "x": 14,
    "y": 2,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_9_2": {
    "id": "guess_9_2",
    "type": 0,
    "x": 15,
    "y": 2,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_9_3": {
    "id": "guess_9_3",
    "type": 0,
    "x": 16,
    "y": 2,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "guess_9_4": {
    "id": "guess_9_4",
    "type": 0,
    "x": 17,
    "y": 2,
    "width": 1,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FPGcG9m2GSI8BCixU?alt=media&token=1890032a-0726-40db-a8bb-9426871e7db8",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': false,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "result_1": {
    "id": "result_1",
    "type": 0,
    "x": 19,
    "y": 10,
    "width": 4,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=1st Result&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?1st Result&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': true,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "result_2": {
    "id": "result_2",
    "type": 0,
    "x": 19,
    "y": 9,
    "width": 4,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=2nd Result&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?2nd Result&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': true,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "result_3": {
    "id": "result_3",
    "type": 0,
    "x": 19,
    "y": 8,
    "width": 4,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=3rd Result&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?3rd Result&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': true,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "result_4": {
    "id": "result_4",
    "type": 0,
    "x": 19,
    "y": 7,
    "width": 4,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=4th Result&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?4th Result&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': true,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "result_5": {
    "id": "result_5",
    "type": 0,
    "x": 19,
    "y": 6,
    "width": 4,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=5th Result&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?5th Result&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': true,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "result_6": {
    "id": "result_6",
    "type": 0,
    "x": 19,
    "y": 5,
    "width": 4,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=6th Result&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?6th Result&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': true,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "result_7": {
    "id": "result_7",
    "type": 0,
    "x": 19,
    "y": 4,
    "width": 4,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=7th Result&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?7th Result&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': true,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },

  "result_8": {
    "id": "result_8",
    "type": 0,
    "x": 19,
    "y": 3,
    "width": 4,
    "height": 1,
    "distThreshold": 1,
    // "previewMessage": "Press x to check.",
    "normal": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=8th Result&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "highlighted": "https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?8th Result&font=Roboto-Regular.ttf&red=255&green=255&blue=255&size=14",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': true,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': false,
    'STACKABLE': true,
    'TRADEABLE': false,
    'LOOTABLE': false,
  },


  "blue-gem_1": {
    "id": "blue-gem_1",
    "type": 5,
    "x": 3,
    "y": 9,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FKlXm4V64UBYuQQuN?alt=media&token=e20f544d-d47d-43f6-8194-c8e1f1e16ddd",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/rW3yhWcgSMrH7RhoyWl6mG",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "blue-gem_2": {
    "id": "blue-gem_2",
    "type": 5,
    "x": 4,
    "y": 9,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FKlXm4V64UBYuQQuN?alt=media&token=e20f544d-d47d-43f6-8194-c8e1f1e16ddd",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/rW3yhWcgSMrH7RhoyWl6mG",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "blue-gem_3": {
    "id": "blue-gem_3",
    "type": 5,
    "x": 5,
    "y": 9,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FKlXm4V64UBYuQQuN?alt=media&token=e20f544d-d47d-43f6-8194-c8e1f1e16ddd",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/rW3yhWcgSMrH7RhoyWl6mG",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "blue-gem_4": {
    "id": "blue-gem_4",
    "type": 5,
    "x": 6,
    "y": 9,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FKlXm4V64UBYuQQuN?alt=media&token=e20f544d-d47d-43f6-8194-c8e1f1e16ddd",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/rW3yhWcgSMrH7RhoyWl6mG",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },

  "red-gem_1": {
    "id": "red-gem_1",
    "type": 5,
    "x": 3,
    "y": 10,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/PXwK0mA3yHtnQPN1PuY6zk",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/snUrorgZCTfalmaq1Pgtkr",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "red-gem_2": {
    "id": "red-gem_2",
    "type": 5,
    "x": 4,
    "y": 10,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/PXwK0mA3yHtnQPN1PuY6zk",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/snUrorgZCTfalmaq1Pgtkr",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "red-gem_3": {
    "id": "red-gem_3",
    "type": 5,
    "x": 5,
    "y": 10,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/PXwK0mA3yHtnQPN1PuY6zk",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/snUrorgZCTfalmaq1Pgtkr",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "red-gem_4": {
    "id": "red-gem_4",
    "type": 5,
    "x": 6,
    "y": 10,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/PXwK0mA3yHtnQPN1PuY6zk",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/snUrorgZCTfalmaq1Pgtkr",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },

  "orange-gem_1": {
    "id": "orange-gem_1",
    "type": 5,
    "x": 3,
    "y": 11,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/OMEKxZ36SZZ4H3AUuTOWol",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/GzYShieBYRz26a56VxHGG4",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "orange-gem_2": {
    "id": "orange-gem_2",
    "type": 5,
    "x": 4,
    "y": 11,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/OMEKxZ36SZZ4H3AUuTOWol",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/GzYShieBYRz26a56VxHGG4",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "orange-gem_3": {
    "id": "orange-gem_3",
    "type": 5,
    "x": 5,
    "y": 11,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/OMEKxZ36SZZ4H3AUuTOWol",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/GzYShieBYRz26a56VxHGG4",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "orange-gem_4": {
    "id": "orange-gem_4",
    "type": 5,
    "x": 6,
    "y": 11,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/OMEKxZ36SZZ4H3AUuTOWol",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/GzYShieBYRz26a56VxHGG4",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },

  "purple-gem_1": {
    "id": "purple-gem_1",
    "type": 5,
    "x": 3,
    "y": 12,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FcckeRLmeMY9R6vF1?alt=media&token=d93ee66d-3341-4674-a66d-c6ad7ad429de",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/ilPdS6pnDwGC6emT8V56Im",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "purple-gem_2": {
    "id": "purple-gem_2",
    "type": 5,
    "x": 4,
    "y": 12,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FcckeRLmeMY9R6vF1?alt=media&token=d93ee66d-3341-4674-a66d-c6ad7ad429de",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/ilPdS6pnDwGC6emT8V56Im",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "purple-gem_3": {
    "id": "purple-gem_3",
    "type": 5,
    "x": 5,
    "y": 12,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FcckeRLmeMY9R6vF1?alt=media&token=d93ee66d-3341-4674-a66d-c6ad7ad429de",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/ilPdS6pnDwGC6emT8V56Im",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "purple-gem_4": {
    "id": "purple-gem_4",
    "type": 5,
    "x": 6,
    "y": 12,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FcckeRLmeMY9R6vF1?alt=media&token=d93ee66d-3341-4674-a66d-c6ad7ad429de",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/ilPdS6pnDwGC6emT8V56Im",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },

  "green-gem_1": {
    "id": "green-gem_1",
    "type": 5,
    "x": 3,
    "y": 13,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2F9Yww3v4mr4Riru4w?alt=media&token=2912e83d-0076-4210-8fd3-b7fcd2efb05d",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/CCGQKIzvNUWyJYcXJp7Kdk",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "green-gem_2": {
    "id": "green-gem_2",
    "type": 5,
    "x": 4,
    "y": 13,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2F9Yww3v4mr4Riru4w?alt=media&token=2912e83d-0076-4210-8fd3-b7fcd2efb05d",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/CCGQKIzvNUWyJYcXJp7Kdk",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "green-gem_3": {
    "id": "green-gem_3",
    "type": 5,
    "x": 5,
    "y": 13,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2F9Yww3v4mr4Riru4w?alt=media&token=2912e83d-0076-4210-8fd3-b7fcd2efb05d",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/CCGQKIzvNUWyJYcXJp7Kdk",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "green-gem_4": {
    "id": "green-gem_4",
    "type": 5,
    "x": 6,
    "y": 13,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2F9Yww3v4mr4Riru4w?alt=media&token=2912e83d-0076-4210-8fd3-b7fcd2efb05d",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/CCGQKIzvNUWyJYcXJp7Kdk",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },

  "gray-gem_1": {
    "id": "gray-gem_1",
    "type": 5,
    "x": 3,
    "y": 14,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/RItc5gsMEhLSntGIV8YVUW",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/fsgnsf3nrdYY3PfCHq1Zav",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "gray-gem_2": {
    "id": "gray-gem_2",
    "type": 5,
    "x": 4,
    "y": 14,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/RItc5gsMEhLSntGIV8YVUW",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/fsgnsf3nrdYY3PfCHq1Zav",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "gray-gem_3": {
    "id": "gray-gem_3",
    "type": 5,
    "x": 5,
    "y": 14,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/RItc5gsMEhLSntGIV8YVUW",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/fsgnsf3nrdYY3PfCHq1Zav",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },
  "gray-gem_4": {
    "id": "gray-gem_4",
    "type": 5,
    "x": 6,
    "y": 14,
    "width": 1,
    "height": 1,
    "distThreshold": 2,
    "previewMessage": "Press [Spacebar] to pick up.",
    "normal": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/RItc5gsMEhLSntGIV8YVUW",
    "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/fsgnsf3nrdYY3PfCHq1Zav",
    "customState": "none",
    'COOLDOWN': 0,
    'BEHAVIOR': 'none',
    'FIXED': false,
    'LOGIC': 'none',
    'DOORS': 'none',
    'SWAPPABLE': true,
    'STACKABLE': false,
    'TRADEABLE': true,
    'LOOTABLE': true,
    
  },

    // "sneaker": {
    //   "id": "sneaker",
    //   "type": 5,
    //   "x": 5,
    //   "y": 5,
    //   "width": 1,
    //   "height": 1,
    //   "distThreshold": 2,
    //   "previewMessage": "Press space to pick up",
    //   "normal": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/Bs1hREmzgcBbhQTq/1h3wwUzJ7Mdadt4KGfIwf5",
    //   "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/Bs1hREmzgcBbhQTq/1h3wwUzJ7Mdadt4KGfIwf5",
    //   "customState": "none",
    //   'COOLDOWN': 0,
    //   'BEHAVIOR': 'none',
    //   'FIXED': false,
    //   'LOGIC': 'none',
    //   'DOORS': 'none',
    //   'SWAPPABLE': true,
    //   'STACKABLE': true,
    //   'TRADEABLE': true,
    //   'LOOTABLE': true,

    // },

    // "spot_1": {
    //   "id": "spot_1",
    //   "type": 0,
    //   "x": 14,
    //   "y": 11,
    //   "width": 1,
    //   "height": 1,
    //   "distThreshold": 2,
    //   // "previewMessage": "",
    //   "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FYEeExcvH2DBnZsrI?alt=media&token=1b8fcb20-960f-40ec-b8b8-2a8496123e59",
    //   "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FYEeExcvH2DBnZsrI?alt=media&token=1b8fcb20-960f-40ec-b8b8-2a8496123e59",
    //   "customState": "none",
    //   'COOLDOWN': 0,
    //   'BEHAVIOR': 'none',
    //   'FIXED': true,
    //   'LOGIC': 'none',
    //   'DOORS': 'none',
    //   'SWAPPABLE': false,
    //   'STACKABLE': true,
    //   'TRADEABLE': false,
    //   'LOOTABLE': false,
      
    // },

    // "spot_2": {
    //   "id": "spot_2",
    //   "type": 0,
    //   "x": 15,
    //   "y": 11,
    //   "width": 1,
    //   "height": 1,
    //   "distThreshold": 2,
    //   // "previewMessage": "",
    //   "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FYEeExcvH2DBnZsrI?alt=media&token=1b8fcb20-960f-40ec-b8b8-2a8496123e59",
    //   "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FYEeExcvH2DBnZsrI?alt=media&token=1b8fcb20-960f-40ec-b8b8-2a8496123e59",
    //   "customState": "none",
    //   'COOLDOWN': 0,
    //   'BEHAVIOR': 'none',
    //   'FIXED': true,
    //   'LOGIC': 'none',
    //   'DOORS': 'none',
    //   'SWAPPABLE': false,
    //   'STACKABLE': true,
    //   'TRADEABLE': false,
    //   'LOOTABLE': false,
      
    // },


    // "spot_3": {
    //   "id": "spot_3",
    //   "type": 0,
    //   "x": 16,
    //   "y": 11,
    //   "width": 1,
    //   "height": 1,
    //   "distThreshold": 2,
    //   // "previewMessage": "",
    //   "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FYEeExcvH2DBnZsrI?alt=media&token=1b8fcb20-960f-40ec-b8b8-2a8496123e59",
    //   "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FYEeExcvH2DBnZsrI?alt=media&token=1b8fcb20-960f-40ec-b8b8-2a8496123e59",
    //   "customState": "none",
    //   'COOLDOWN': 0,
    //   'BEHAVIOR': 'none',
    //   'FIXED': true,
    //   'LOGIC': 'none',
    //   'DOORS': 'none',
    //   'SWAPPABLE': false,
    //   'STACKABLE': true,
    //   'TRADEABLE': false,
    //   'LOOTABLE': false,
      
    // },

    // "spot_4": {
    //   "id": "spot_4",
    //   "type": 0,
    //   "x": 17,
    //   "y": 11,
    //   "width": 1,
    //   "height": 1,
    //   "distThreshold": 2,
    //   // "previewMessage": "",
    //   "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FYEeExcvH2DBnZsrI?alt=media&token=1b8fcb20-960f-40ec-b8b8-2a8496123e59",
    //   "highlighted": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FYEeExcvH2DBnZsrI?alt=media&token=1b8fcb20-960f-40ec-b8b8-2a8496123e59",
    //   "customState": "none",
    //   'COOLDOWN': 0,
    //   'BEHAVIOR': 'none',
    //   'FIXED': true,
    //   'LOGIC': 'none',
    //   'DOORS': 'none',
    //   'SWAPPABLE': false,
    //   'STACKABLE': true,
    //   'TRADEABLE': false,
    //   'LOOTABLE': false,
      
    // },

              
  }
}


}

// Indicator
// https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FYEeExcvH2DBnZsrI?alt=media&token=1b8fcb20-960f-40ec-b8b8-2a8496123e59

// Opened Doors
// https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/Ho6abUIslqoWcDQ7/FX06IIOJrhvZZAhzgpoono

// https://2y74lxqi4a.execute-api.us-west-2.amazonaws.com/dev/draw-text?text=G&font=Roboto-Bold.ttf&red=0&green=0&blue=0&size=48

// G 32px
// https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/TeIhehUps0bqloK9PX3aCY

// G White
// https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/CQ39Ni8TvuiHX7fV2JGovH


// blue-gem.png
// https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FKlXm4V64UBYuQQuN?alt=media&token=e20f544d-d47d-43f6-8194-c8e1f1e16ddd

// blue-gem-highlighted.png
// https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/rW3yhWcgSMrH7RhoyWl6mG

// red-gem.png
// https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/PXwK0mA3yHtnQPN1PuY6zk

// red-gem-highlighted.png
// https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/snUrorgZCTfalmaq1Pgtkr

// orange-gem.png
// https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/OMEKxZ36SZZ4H3AUuTOWol

// orange-gem-highlighted.png
// https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/GzYShieBYRz26a56VxHGG4

// purple-gem.png
// https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FcckeRLmeMY9R6vF1?alt=media&token=d93ee66d-3341-4674-a66d-c6ad7ad429de

// purple-gem-highlighted.png
// https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/ilPdS6pnDwGC6emT8V56Im

// green-gem.png
// https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2F9Yww3v4mr4Riru4w?alt=media&token=2912e83d-0076-4210-8fd3-b7fcd2efb05d

// green-gem-highlighted.png
// https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/CCGQKIzvNUWyJYcXJp7Kdk

// gray-gem.png
// https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/RItc5gsMEhLSntGIV8YVUW

// gray-gem-highlighted.png
// https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/fsgnsf3nrdYY3PfCHq1Zav


// "blue-gem_1": {
//   "id": "blue-gem_1",
//   "type": 5,
//   "x": 3,
//   "y": 9,
//   "width": 1,
//   "height": 1,
//   "distThreshold": 2,
//   "previewMessage": "Press [Spacebar] to pick up.",
//   "normal": "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FKlXm4V64UBYuQQuN?alt=media&token=e20f544d-d47d-43f6-8194-c8e1f1e16ddd",
//   "highlighted": "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/kuOpQ63ckdxpfANU/rW3yhWcgSMrH7RhoyWl6mG",
//   "customState": "none",
//   'COOLDOWN': 0,
//   'BEHAVIOR': 'none',
//   'FIXED': false,
//   'TRADEABLE': true,
//   'LOOTABLE': true,
//   'SWAPPABLE': true,
//   'STACKABLE': true,
//   'LOGIC': "none",
//   'DOORS': "none",


  
// },